#!/usr/bin/python2.7

'''
WEEELAB - Log management module for garbaging paper sign sheet.
Author: Stefano Enrico Mendola (aka Hyd3L, STE col teschio)

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
'''

import os
import sys
from datetime import datetime

VERSION = "1.4"
EXECNAME = "weeelab"
HOSTNAME = "schifomacchina"
HOSTUSER = "weeeopen"
LOG_PATH = "/home/"+HOSTUSER+"/.local/share/"+EXECNAME+"/log.dat"
USERS_PATH = "/home/"+HOSTUSER+"/.local/share/"+EXECNAME+"/users.dat"
BACKUP_PATH = "/home/"+HOSTUSER+"/ownCloud/weeeopen/"+EXECNAME.capitalize()+"/"


def help(forWhat):
    if forWhat == "login":
        print "usage: " + EXECNAME + " login <username>"
        print HOSTNAME + ": Username format is 'first.last' or 'XXXXXX'"
        print "                where XXXXXX is your serial number."
        print "                You can even use an alias if defined."
        sys.exit()

    elif forWhat == "logout":
        print "usage: " + EXECNAME + " logout <username>"
        print HOSTNAME + ": Username format is 'first.last'"
        print "                where XXXXXX is your serial number."
        print "                You can even use an alias if defined."
        sys.exit()

    elif forWhat == "show":
        print "usage: "+EXECNAME+" show <option>"
        print "  available options:"
        print "      log : Print log file to stdout."
        print "    inlab : View a list of students in lab now."
        sys.exit()

    elif forWhat == "stat":
        print "usage: "+EXECNAME+" stat <username>"
        print HOSTNAME+": If you want to view stats for everybody,"
        print "                use \""+EXECNAME+" stat all\""

    elif forWhat == "top":
        print "usage: "+EXECNAME+" top <list_length>"

    else:
        print "WEEELAB v"+VERSION+" - Log management module for garbaging paper sign sheet."
        print "Author: Stefano Enrico Mendola (aka Hyd3L, STE col teschio)"
        print "Copyright (C) 2017 WeeeOpen - Politecnico di Torino"
        print "This program comes with ABSOLUTELY NO WARRANTY."
        print "Since this is a free software, you are welcome"
        print "to redistribute it under the terms of the GNU GPLv3.\n"
        print "  Available commands:"
        print "    login  <username> : Sign access to the lab."
        print "    logout <username> : Sign quit from the lab."
        print "    show   <option>   : Retrieve informations."
        print "    stat   <username> : Compute stats for a user or for all users."
        print "    top <list_length> : Show a list of top <list_length> members."
        sys.exit()


# Check if log file exists.
def checkLogFile():
    if os.path.isfile(LOG_PATH) is False:
        print "error: Log file not found."
        sys.exit()


# Check if users list file exists.
def checkUsersFile():
    if os.path.isfile(USERS_PATH) is False:
        print "error: Users list not found."
        sys.exit()


# Check if an username exists in users list file.
def checkMember(username):
    checkUsersFile()
    found = False
    usersFile = open(USERS_PATH, "r")

    for line in usersFile:
        # Remove newline character from the line read from file
        line = line.replace("\n","")
        words = line.split()
        if username in words:
            found = True
            username = words[0]
            break
    usersFile.close()

    if not found:
        print "error: Username not recognized."
        print HOSTNAME + ": Maybe you misspelled it or you're an intruder."
        sys.exit()
    return username


# Check if user is already logged in.
def isLoggedIn(username):
    username = checkMember(username)
    logged = False
    logFile = open(LOG_PATH, "r")
    for line in logFile:
        if ("INLAB" in line) and (username in line):
            logged = True
            break
    logFile.close()
    return logged


def nameExtr(username):
    firstName = username.split('.')[0].capitalize()
    lastName = username.split('.')[1].capitalize()
    return firstName + " " + lastName


# Check if inputFile is empty.
def isEmpty(inputFile):
    if str(inputFile.read())[:1] == "":
        inputFile.close()
        return True
    else:
        inputFile.seek(0)
        return False


def createBackupIfNecessary():
    logFile = open(LOG_PATH, "r")
    if isEmpty(logFile) is False:
        lastLine = str(logFile.read())[4:11]
        logFile.close()

        currMonth = int(datetime.now().strftime("%m"))
        currYear = int(datetime.now().strftime("%Y"))
        lastMonth = int(datetime.now().strptime(lastLine,"%m/%Y").strftime("%m"))
        lastYear = int(datetime.now().strptime(lastLine,"%m/%Y").strftime("%Y"))

        if (currMonth > lastMonth) or (currYear > lastYear):
            print HOSTNAME + ": Backing up log file... ",
            newPath = LOG_PATH[:len(LOG_PATH)-4] + str(lastYear) + str(lastMonth).zfill(2)+".dat"
            os.rename(LOG_PATH, newPath)
            # Send to ownCloud folder
            os.system("cp "+newPath+" "+BACKUP_PATH+"log"+str(lastYear)+str(lastMonth).zfill(2)+".txt")
            print "Done!"
            logFile = open(LOG_PATH, "w")
            logFile.close()
            print HOSTNAME + ": New log file was created."


def login(username):
    checkLogFile()
    createBackupIfNecessary()
    username = checkMember(username)
    currTime = datetime.now().strftime("%d/%m/%Y %H:%M")
    loginString = "["+currTime+"] "+"[----------------] [INLAB] "+"<"+username+">"+"\n"

    if isLoggedIn(username):
        print HOSTNAME + ": " + nameExtr(username) + ", you're already logged in."
    else:
        logList = []
        logList.append(loginString)

        logFile = open(LOG_PATH, "r")
        for line in logFile:
            logList.append(line)
        logFile.close()

        logFile = open(LOG_PATH, "w")
        for line in logList:
            logFile.write(line)
        logFile.close()
        # Send to ownCloud folder
        os.system("cp "+LOG_PATH+" "+BACKUP_PATH+"log.txt")
        print HOSTNAME + ": Login successful! Hello " + nameExtr(username) + "!"


# Returns the time spent in lab formatted as HH:MM
def workTime(timein, timeout):
    li = (int(timein[:2]) * 60) + int(timein[3:5])
    lo = (int(timeout[:2]) * 60) + int(timeout[3:5])
    hours = (lo - li) / 60
    minutes = (lo - li) % 60
    return str(hours).zfill(2)+":"+str(minutes).zfill(2)


def logout(username):
    checkLogFile()
    username = checkMember(username)
    currTime = datetime.now().strftime("%d/%m/%Y %H:%M")
    found = False

    logList = []
    logFile = open(LOG_PATH, "r")
    for line in logFile:
        if ("INLAB" in line) and (username in line):
            found = True
            loginTime = line[12:17]
            logouTime = currTime[11:17]
            line = line.replace("----------------",currTime)
            line = line.replace("INLAB",workTime(loginTime,logouTime))
            line = line.replace("\n","")
            workdone = raw_input(HOSTNAME+": What have you done?\n:: ")
            while len(workdone) > 128:
                print HOSTNAME+": I didn't ask you the story of your life!"
                workdone = raw_input(HOSTNAME+": What have you done? [BRIEFLY]\n>> ")
            line = line + " :: " + workdone + "\n"
        logList.append(line)  # Store everything in the list
    logFile.close()

    if found:
        # Writing everything to log file
        logFile = open(LOG_PATH, "w")
        for line in logList:
            logFile.write(line)
        logFile.close()
        # Send to ownCloud folder
        os.system("cp "+LOG_PATH+" "+BACKUP_PATH+"log.txt")
        print HOSTNAME + ": Logout successful! Bye " + nameExtr(username) + "!"
    else:
        print HOSTNAME + ": " + nameExtr(username) + " is not in lab!"


def show(option):
    checkLogFile()

    if option == "log":
        print HOSTNAME + ": Reading log file...\n"
        logFile = open(LOG_PATH, "r")
        for line in logFile:
            print line,
        logFile.close()

    elif option == "inlab":
        count = 0
        currDay = datetime.now().strftime("%d/%m/%Y")
        print HOSTNAME + ": Reading log file...\n"
        logFile = open(LOG_PATH, "r")
        for line in logFile:
            if ("INLAB" in line) and (currDay in line):
                count += 1
                print "> " + nameExtr(line[47:line.rfind(">")])
        logFile.close()

        if count == 0:
            print HOSTNAME + ": Nobody is in lab right now."
        elif count == 1:
            print HOSTNAME + ": There is one student in lab right now."
        else:
            print HOSTNAME + ": There are {c} students in lab right now.".format(c=count)

    elif option == "help":
        help("default")

    # Uovo di Pasqua
    # elif option == "beer":
    #     print HOSTNAME + ": Sadly my constructors haven't considered to add"
    #     print "                such component in my system, but I could hold your"
    #     print "                beer if you want [Y/n]",
    #     response = raw_input()
    #     if response == "y" or response == "Y" or response == "":
    #         os.system("eject /dev/cdrom")
    #         print HOSTNAME + ": Alright! Lean here your beer :-)"
    #     else:
    #         print HOSTNAME + ": As you desire! :-)"
    # else:
    #     print "error: Invalid option detected."
    #     print HOSTNAME + ": Try with 'help show'."

    else:
        print "error: option "+option+" is not defined."


# Returns total work time in minutes
def totWorkTime(username):
    checkLogFile()
    timeSpent = 0
    logFile = open(LOG_PATH, "r")
    for line in logFile:
        if (username in line) and not ("INLAB" in line):
            timeSpent += ((int(line[39:41])*60) + int(line[42:44]))
    logFile.close()
    return timeSpent


# Convert minutes in a formatted string
def timeConv(minutes):
    return str(minutes / 60)+"h " + str(minutes % 60)+"m"


def stat(username):
    print HOSTNAME+": Computing stats...\n"
    currMonth = datetime.now().strftime(" [%B %Y]")

    # Compute stats for all users (Extremely stupid algorithm, but works fine)
    if username == "all":
        checkUsersFile()
        usersFile = open(USERS_PATH, "r")
        for line in usersFile:
            currUser = line.split(" ")[0]
            print "[+]     Name: "+nameExtr(currUser)
            print "[+] WorkTime: "+timeConv(totWorkTime(currUser)) + currMonth+"\n"
        usersFile.close()

    else:
        username = checkMember(username)
        print "[+]     Name: "+nameExtr(username)
        print "[+] WorkTime: "+timeConv(totWorkTime(username)) + currMonth


# Print users list ordered by most active first.
def top(length):
    checkUsersFile()
    usersList = [(int, str)]
    usersFile = open(USERS_PATH, "r")

    # Loading usernames from file
    for line in usersFile:
        usersList.append((0, line.split(" ")[0].replace("\n","")))
    usersFile.close()
    usersList.remove((int, str))

    # Computing total work time for each member
    for i in xrange(0,len(usersList)):
        user = usersList[i]
        user = (totWorkTime(user[1]), ) + user[1:]
        usersList[i] = user
    usersList.sort(reverse=True)

    print HOSTNAME+": Hall of Fame\n"
    count = 1
    for i in xrange(0, length):
        if len(usersList) <= i:
            break
        print "["+str(count).zfill(2)+"] "+nameExtr(usersList[i][1])
        count += 1


def main(args):
    if len(args) < 2:
        print "usage: "+EXECNAME+" <command> <arguments>"
        sys.exit()
    command = args[1]

    # Add commands here
    if command == "help":
        if len(args) < 3:
            help("default")
        elif len(args) >= 3:
            help(args[2])

    elif command == "login":
        if len(args) != 3:
            print "usage: "+EXECNAME+" login <username>"
            sys.exit()
        else:
            login(args[2])

    elif command == "logout":
        if len(args) != 3:
            print "usage: "+EXECNAME+" logout <username>"
            sys.exit()
        else:
            logout(args[2])

    elif command == "show":
        if len(args) != 3:
            print "usage: "+EXECNAME+" show <option>"
            print "  available options:"
            print "      log : Print log file to stdout."
            print "    inlab : View a list of students in lab now."
            sys.exit()
        else:
            show(args[2])

    elif command == "stat":
        if len(args) != 3:
            print "usage: "+EXECNAME+" stat <username>"
            sys.exit()
        else:
            stat(args[2])

    elif command == "top":
        if len(args) == 3:
            if args[2].isdigit is False:
                print "usage: "+EXECNAME+" top <list_length>"
            else:
                top(int(args[2]))
        else:
            top(10)

    else:
        print "error: Invalid command detected -> " + args[1]
        print HOSTNAME + ": Try with \""+EXECNAME+" help\""


if __name__ == '__main__':
    main(sys.argv)
