[db]
name = "grillo"
host = "localhost"
port = 5432
user = "weeelab"
password = "weeelab"

[ldap]
host = "ldap://ldap.example.com"
bind_dn = "cn=something,dc=example,dc=com"
password = "foo"
tree = "ou=People,dc=example,dc=com"

[tmp]
path = "tmp_audits"
